version: '3.9'

services:
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www

  web:
    image: nginx
    ports:
      - 8070:8000
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf